### ISSUE TITLE
Push notifications elk les uur op je computer.

### ISSUE THREAD

**Issue by HjalmarSnoep** [MediacollegeAmsterdam/presentietool#1]
Voor de studenten handig. Ik denk erover na, is best veel werk.
Laat even weten of je het zou willen hebben met een  Duimpje omhoog..
En of je het NIET wil hebben met een Duimpje omlaag..

**Comment by StefvanEgmond** [comment]
+1

**Comment by HjalmarSnoep** [comment]
Nog maar eentje, gelukkig, anders moest ik aan de bak :)

**Comment by DylanStruik** [comment]
+1

**Comment by steffalon** [comment]
+1

**Comment by Quenten** [comment]
+1

**Comment by YouSeeStefan** [comment]
+1

**Comment by RicoSchwab12** [comment]
+1

**Comment by Nino-dev** [comment]
Doe maar wel, vergeet het elke keer.
